legacy:
  uri: ${LEGACY_URI:http://localhost:8081/api}

dateFrom: ${DATEFROM:10-15-1999}
dateTo: ${DATETO:08-11-2024}

server:
  servlet:
    context-path: /api
spring:
  application:
    name:
      hospital
  datasource:
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:admin}
    url: jdbc:mysql://${MYSQL_HOST:localhost:3307}/${MYSQL_DB_NAME:hospital}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
